---
- name: Configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yaml
  vars:
    - dbname: "notes"
    - dbusername: "notesapp"
    - dbpassword: "password"
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql
