
Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  
  config.vm.provision "shell", path: "provision.sh"

  #config.vbguest.auto_update = false
  #config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"

end
