---
mysql_root_password: password
mysql_databases:
  - name: notes
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: notesapp
    host: "%"
    password: password
    priv: "notes.*:ALL"
    