
Vagrant.configure("2") do |config|

  # configuração no nome (hostname) da vm do banco - db01
  config.vm.hostname = "db01"

  # configuração do SO/distro a ser utilizada
  config.vm.box = "centos/7"

  # configuração do ip local da vm
  config.vm.network "private_network", ip: "192.168.56.4"

  # mapeamento de portas do banco - portas padrão para o mysql
  config.vm.network "forwarded_port", guest: 3306, host: 3306

  # mapeamento dos comandos bash para instalação configuração de relacao de confiança entre 
  config.vm.provision "shell", path: "provision.sh"

  # configuração para habilitação do plugin vbox para integrar com o vagrant
  config.vbguest.auto_update = false
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
end
